---

- name: configure | Create solr Directory.
  file: path={{ solr_datadir }} state=directory owner={{ solr_user }} group={{ solr_user }}

- name: configure | Set solr.in.sh file.
  template:
    dest: "{{ solr_dir }}/solr.in.sh"
    mode: 0644
    src: solr.in.sh.j2
    owner: "{{ solr_user }}"
    group: "{{ solr_user }}"

- name: configure | Set solr init script.
  template:
    dest: "/etc/init.d/{{ solr_name }}"
    mode: 0755
    src: solr.init.j2

- name: configure | Add solr services.
  shell: "chkconfig --add {{ solr_name }} && chkconfig {{ solr_name }} on"

- name: configure | Ensure solr is started .
#  service: "name={{ solr_name }} state=started enabled=yes" 
  command: "service {{ solr_name }} start"
  ignore_errors: yes

- name: configure | Wait for solr port is OPEN.
  wait_for: "port={{ solr_port }} state=started"
